


"""
Django settings for jason_wellness project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR =os.path.join(BASE_DIR,'templates')
STATIC_DIR = os.path.join(BASE_DIR,'static')
REPOSITORY_ROOT= os.path.dirname(BASE_DIR)






# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mima8^^t85_64er*cbw376dvjms%n-!5!sz4x511j$8#@pc_96'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# CORS_ORIGIN_ALLOW_ALL = True

ALLOWED_HOSTS = ['*','localhost']


PARENT_MNEMONIC = "actual address hello all engine utility expose farm inside rate divert garment"


CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'token',  # Add your custom header here
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'django_tables2',
    'django_ajax',
    'django_filters',
    'crispy_forms',
    'django_user_agents',
    'ckeditor',
    'simple_history',
    'storages',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'themesettings',
    'trade_admin_auth',
    'locations',
    'company',
    'trade_master',
    'trade_currency',
    'trade_auth',
    'API',
    'Staking'
]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.common.CommonMiddleware'
# ]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]


# 👇 Add this line here
CORS_ORIGIN_ALLOW_ALL = True



ROOT_URLCONF = 'jason_wellness.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

WSGI_APPLICATION = 'jason_wellness.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(REPOSITORY_ROOT, 'static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(REPOSITORY_ROOT, 'media/')

# Ensure the folder structure exists
os.makedirs(os.path.join(MEDIA_ROOT, 'images'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'videos'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'documents'), exist_ok=True)


COMMON_ENCRYPTION_KEY= b'asdjk@15r32r1234asdsaeqwe314SEFT'
COMMON_16_BYTE_IV_FOR_AES= b'IVIVIVIVIVIVIVIV'


AWS_SES_FROM='5cpjPUPqiU1yB2kctcVycPP1LLPgz7q9K/gzAvQvK9E='
MAIL_BACK = '50ngkIqyycdOhYML6jg7eSwlB+CwXayTfJtOq1O8ehUgZPIB5462DSWy21hUqeBu'
MAIL_HOST = 'Dvhbn3iDh6VsyQvMrtpNfw=='
MAIL_PORT = 'LhdPUJXE7CW5i6D0P5VNEQ=='
MAIL_HOST_USER = '5cpjPUPqiU1yB2kctcVycPP1LLPgz7q9K/gzAvQvK9E='
MAIL_HOST_PASSWORD = 'xjCPdYFSxNgFqv9L813FyVasgUKcAi3J4eO1gUNnXs7IQudoLCINk6DwfnDiPSDd8C+2OqidLhZsY8kyRNEjuQ=='
MAIL_API = "Gv0aw7HGP4vorJ5zrdgDpgccMO3mRMapjumd/tfvw6fRrmZW7HantwKng3fqJMou+yyIbldMg+u9Ucw3wVkwwQ=="


EMAIL_USER = ''
# EMAIL_BACKEND = ''
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Correct value
EMAIL_HOST = ''
EMAIL_PORT = 0
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True


DOMAIN_URL='pip.jasanwellness.fit'

AWS_ACCESS_KEY_ID = 'AKIAYDX56ZL7CQNBTCOQ'
AWS_SECRET_ACCESS_KEY = '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'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_STORAGE_BUCKET_NAME = 'jasanwellnessnews3'
AWS_S3_REGION_NAME = 'us-east-1'
AWS_DEFAULT_ACL = "public-read"

# from jason_wellness.jason_wellness_settings import *
# from jason_wellness.jason_database import *
